### ISSUE TITLE
simple-http

### ISSUE THREAD

**Issue by torstenandrecht** [SourceFellows/gobuch#1]
I think there is an error in the main.go for simple-http

current implementation:
http.HandleFunc("/a/", handleHttp)

correct implementation:
http.HandleFunc("/",  handleHttp)

**Comment by SourceFellows** [comment]
Hi,

thanks for the hint. I "corrected" the implementation. 
The sample worked but not as expected ;-)

Thanks,
Kristian

ps: I remember that i had caching issues with this sample so I changed the Handler-Mapping to something other than "/".
